### ISSUE TITLE
[Question] How did you bind the node runtime to linux boot?

### ISSUE THREAD

**Issue by michaelspeed** [eXtern-OS/eXternOS-Base#1]
How did you bind the node runtime to linux boot?

Any window manager?
PS: i would like to contribute

**Comment by anesuc** [comment]
Hi Risha!

The node runtime is within Nw.js which comes with Node.js as part of it. It starts in the same way any XSession does. If you are looking into doing something like this, I would recommend just look up how to create a custom session as there is a few ways to do it. The window manager is currently Kwin. I have changed around a lot during the development of this and would like a more light weight option (but with good animations and blur support) as I have to include a lot of KDE resources to make it work. One option I am waiting to see if it gets stable enough is https://github.com/yshui/picom which was previously known as compton (it's a fork of it). I almost went with that option for Beta 2 and made a last minute change as it was wildly unpredictable based on the user's hardware and as it is already, people are ignoring the minimum system requirements listed haha.

About contributions, currently I would recommend joining the dev team as we are doing a lot of internal changes that require close communication before any additional changes. That's part of the reason the code is slowly being released, it's because there is a lot of internal changes going on. Plus attempting to clean up the code as we go, but that's another story haha. Before considering to join though, you need to make sure you actually have time to contribute (at least something per week). Actually put some thought into that last point as a lot of people just assume they do, but realistically they don't!

**Comment by michaelspeed** [comment]
`you need to make sure you actually have time to contribute (at least something per week)` This is one i can definitely do
But i am all Node JS so now trying to understand the node bindings with ubunut

**Comment by anesuc** [comment]
You are good with front-end as well? Like HTML, JS, CSS?

**Comment by michaelspeed** [comment]
i am good at react(5 years), vue(3 years) , angular(3 years) , vanilla js(forgot how many years) , HTML , CSS, and node server, basically any node JS related

**Comment by michaelspeed** [comment]
i can only find 4 app on the organisation but there are total 11 added i think?

**Comment by anesuc** [comment]
Ok great! I'll email you the details to our discord server and we'll get you started! Is your email listed on GitHub fine to send the details to?

**Comment by michaelspeed** [comment]
yes, you can send me there also ,or on risha@iiiana.com

**Comment by anesuc** [comment]
> i can only find 4 app on the organisation but there are total 11 added i think?

As I mentioned earlier, we are still adding them (also noted in the README of this) for reasons mentioned above.

**Comment by anesuc** [comment]
> yes, you can send me there also ,or on [risha@iiiana.com](mailto:risha@iiiana.com)

Ok great!
