### ISSUE TITLE
My Experience & Needed Improvements

### ISSUE THREAD

**Issue by ghost** [eXtern-OS/eXternOS-Base#5]
I installed ExternOS today and may I just say I am incredibly blown away by your incredible looking desktop experience. The user experience is faulty but wonderful. I would love to keep this OS on my daily driver if it weren't for a few issues (and yes I know it's not meant to be a daily driver yet, but please bear with me)
I didn't want to just remove your OS and not think twice about it, no, this distribution has so much potential to it and I'd hate for some issues to possibly go unnoticed and stall further development. Below were the first things I noticed:
1) On my laptop, the Start screen (for a lack of a better name) takes up about my entire screen, with no way to change it's size or my resolution. The other elements are fine, but the bare-bones apps on my system shouldn't have icons bigger than the ones in my taskbar. 
2) Tooltips on the notification area. If I hover over the Volume icon, it displays a little tooltip that is cut off by the top of the bar. This could just be my laptop, but it's fairly annoying, and it should probably either overlap the edge (which may not be possible based on how the taskbar is written) or it should adapt it's size based on how much room it has.
3) This desktop is KDE riddled. Your main claim is that it uses almost all web technologies thanks to Node.js but upon first glance I see the KDE window manager header. That's fine, I don't expect developers to write something like a window manager from scratch, but they shouldn't use the default theme! Look at the rest of your OS, it is sleek, has beautiful transparency, and has a totally different style than your window manager. I get you don't want to write a KDE theme or things of the such, and I understand. I suggest using something like Openbox with a basic theme from Openbox Styles (for space, since your desktop appears to not rely on KDE anywhere else) instead of KDE. I don't know if the background is ran by KDE, but it doesn't appear so as far as I can tell. Openbox could reduce the required specifications a tad bit and allow you to create a theme easier that fits the OS better.
4) Native Linux App support is weak, and I mean really weak. It doesn't show up in system resources, nor the start menu, nor anywhere. I have to start apps from the Terminal. **Yes**, I did enable the native app support in the start menu. Your store also only has support for apps you already built. I get what direction you are pushing the store in, but maybe add Flatpak or APT support to it for the time being, since no apps are really on it yet?
5) There are some GNOME apps installed, some KDE apps installed, the GNOME system settings AND KDE system settings are installed... what's going on here? Maybe use a single system control panel and stick with it, or write your own into the start menu like you're already started doing... don't include 3 different desktop environment apps into the base image, especially not when they do the same things as your built-in apps. (I saw GNOME photo viewer... Document Viewer, Text Editor, Archive Manager, KDE System Settings, GNOME Settings, GNOME Tweaks... all this stuff really shouldn't be included if you are writing your own apps to replace them, it takes up more space than needed and winds up not looking good)
6) The taskbar isn't very responsive when it comes to running applications. I understand this, it's likely a limitation with Node.js, but it's annoying nonetheless. Perhaps writing a custom handler to integrate into Node.js could help with this, that way you have better access to core system APIs. 
7) The start menu doesn't start most Linux apps properly, but the terminal does. Also, you are using way too much of Ubuntu's base in this OS. If you follow my openbox suggestion, you can build a minimal Linux system with Buildroot that has support for Openbox and whatever other APIs you need, including Node.js. I can help you with this. Ubuntu isn't exactly the best base to use when you are rewriting the entire UI anyway, maybe try Debian if your own compiled system sounds like too much work, but not the entirety of Ubuntu.

I may have more things to say as I test the OS more. I'm really trying to not be a jerk and if I'm not understanding something PLEASE explain to me why it's there and maybe I can help you here, I want to see this OS flourish but if it's going to be bloated and glitchy it's going to stay in Beta for longer. I can help with Buildroots and possibly some Node.js code depending on how complex it gets.

Thank you for your time and your incredible OS.

**Comment by anesuc** [comment]
Hi William,

Thanks for the feedback, really appreciate it! 

I won't go into detail with every point you've made here as it's a lot and internally we've already addressed most of it or in the process of doing so! So I would suggest you wait for Beta 3. About the mix of KDE and Gnome Apps, the project started on a base of Ubuntu initially which had a lot of Gnome elements. However the window manager didn't support the blur effects that I wanted eXtern OS to have. I tried another standalone window manager but that wasn't really ready and not stable yet [picom](https://github.com/yshui/picom). I also used openbox (I think it's actually still installed haha). But at the end of the day with the window manager had very specific config file thing that needed to be done per system bases (intel integrated/nvidia/amd) and the experience varied wildly with my tests on different systems. I almost knew it would be nightmare if it didn't just work out of the box for most people. I spent waaay too much time trying to get this to work because it would have resulted in faaaar less bloat. I just noticed there has been a lot of updates to picom when searching for that link so might give it another go. With that said, the current Beta 3 doesn't have any Gnome stuff, or barely any. I realise Beta 2 probably barely uses any real time blur by default because I realised close to release time, like a month prior release that half the people were using 2010 - 2013 era desktops when running Linux Destros lol. Some will ignore my comment about not using virtual box which  doesn't really have accelerated graphics at least not talking directly to the GPU unless you have pass-through. But trying to push for it in Beta 3.

Anyway, ended up switching to use KWin as that was far more stable and used a more efficient blur algorithm. Kwin relies on lot of KDE stuff. Especially if you are to perform an update it would install a lot of it even though it's not being used. So until we can get our own window manager, we'll have to rely on KDE.

But yeah don't worry a lot of what you've mentioned, fully aware of it haha. To be honest when that Beta was released, a lot of people were asking for it so ended up rushing it a little bit. We are tying as much as we can to not rush Beta 3 so it's taking a lot more time to come out especially the core development team working on the OS itself is mostly me and the other team members working on the other server related stuff etc. Adding to that I don't have as much time as I used to, so development is slow. I also have another project I am working on that I hope would at least financially bootstrap this project as I have had to financially maintain this mostly out of pocket with servers etc and other things we are working on to come in Beta 3. So that other project did recently get a bit more priority but still working on this just not as fast.

As I mentioned if I was to address every comment you mentioned this would be 5 pages long as you might have realised haha.

**Comment by WillKenzie** [comment]
I love your response and it means a lot that you spent the time looking these things up. I would love to help you in your project and if I can get Buildroot running properly I may even be able to help you build a base that is independent from Ubuntu (It'd be way less bloated and you could use KWin if you want with way less KDE bloat, or Picom easily) 

Also, I think you may know this, but KWin doesn't rely too strongly on most of the things APT says it does. If you compile from scratch you may find less core dependencies, something to consider if you haven't already.

That's all I can really contribute, I'd like to think I could do more in terms of your Node.js work but truth be told I'd probably look at the code and be way too intimidated. If you push your Beta 3 commits I can try to clean up the code as much as possible though, which may provide a speed boost. 

If you don't want a base that is independent from Ubuntu that's fine, it's just something I think could help long-term with making eXtern-OS it's own polished product. I'd recommend and can help with writing your own KWin theme and forcing it as the default, which should be able to make everything feel more fluent.

I will be looking very heavily into this project and I'd love to help as much as I can, just tell me what you want/need and I'll try to help where I can. I can also test it on my laptop to see if I can find any issues in Beta 3 and notify you of them, but I likely won't be able to keep a copy of it on my computer until it's more polished (if what you say is true about Beta 3, then I won't hesitate to install a copy to my computer in a dual boot)

Much appreciation,
Will
