### ISSUE TITLE
Where do I download?

### ISSUE THREAD

**Issue by chrisdebian** [eXtern-OS/eXternOS-Base#8]
Hi,

I got an email from the project, this morning (UK). I'm intrigued by the project, but couldn't see a iso to download. Could you point me to the Nightly or last iso (Beta 2?)

Thanks,

Chris
chris_debian
2E0FRU

**Comment by anesuc** [comment]
Hi Chris,

Thanks for your interest! The downloads for Beta 2 and Beta 1 where removed as I could not handle the support and help requests. It is part of why I am looking for help and funding so that I can actually support this project. I actually took down most of the website for a bit as I had too much going on for my current job that this became too much to handle.

I want to do this properly and give the project the time it deserves which is why you got the email.

Anesu
